name: Build Webapp AMI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: 'Create env file'
      run: |
        touch .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo PORT=${{ secrets.PORT }} >> .env
        cat .env 

    - name: Setup Packer
      uses: hashicorp/setup-packer@main
      with:
        version: '1.8.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Packer Init
      run: packer init .
      continue-on-error: false

    - name: Validate Packer template
      run: packer validate .
      continue-on-error: false

    - name: Build AMI
      run: packer build webapp-ami.pkr.hcl
      continue-on-error: false
