name: Pylint check

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint

    - name: Analysing the code with pylint
      id: pylint
      run: |
        pylint $(git ls-files '*.py') | tee pylint_report.txt | tail -n 3 > pylint_score.txt  # Save the last 3 lines to check for the score
        cat pylint_report.txt

    - name: Extract Pylint Score
      id: extract_score
      run: |
        score=$(tail -n 1 pylint_score.txt | awk '{print $1}')  # Get the score from the last line
        echo "Pylint Score: $score"
        echo "::set-output name=score::$score"  # Set the score as an output variable

    - name: Fail workflow if score is below 7
      if: ${{ fromJson(steps.extract_score.outputs.score) < 7 }}  # Check if score is below 7
      run: |
        echo "Pylint score is below 7. Failing the workflow."
        exit 1
