name: Python Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  python-ci-checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8

    - name: 'Create env file'
      run: |
        touch .env
        echo DB_USER=${{ secrets.DB_USER }} >> .env
        echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> .env
        echo DB_HOST=${{ secrets.DB_HOST }} >> .env
        echo DB_NAME=${{ secrets.DB_NAME }} >> .env
        echo DB_PORT=${{ secrets.DB_PORT }} >> .env
        echo PORT=${{ secrets.APP_PORT }} >> .env
        cat .env   

    - name: Run Flake8
      run: flake8 . --ignore E501,E402

    - name: Run unit tests
      run: pytest tests/test_unit.py --cov=app --cov-report=xml 

    - name: Set up Packer
      uses: hashicorp/setup-packer@v2
      with:
        version: latest

    - name: Packer Init
      run: packer init .
      continue-on-error: false

    - name: Packer Format Check
      run: packer fmt -check -diff .
      continue-on-error: false

    - name: Packer Validate
      run: |
        export $(cat .env | xargs)
        packer validate .
      continue-on-error: false
  
    - name: Packer Build
      env:
        DEV_DEFAUTLT_VPC_ID: ${{ secrets.DEV_DEFAUTLT_VPC_ID }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        packer validate \
          -var "DEV_DEFAUTLT_VPC_ID=$DEV_DEFAUTLT_VPC_ID" \
          -var "AWS_REGION=$AWS_REGION" \
          .
